name: Deploy alevelrevise
on:
  push:
    branches:
      - pages
jobs:
  deploy:
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@v4
      - uses: https://codeberg.org/git-pages/action@v2
        with:
          site: https://www.scottrix.co.uk/
          path: alevelrevise/
          token: ${{ forge.token }}
          source: .
